name: nowcasting_dataset
channels:
  - pytorch
  - pvlib
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - gitpython
  - pydantic

  # Scientific Python
  - numpy
  - pandas
  - matplotlib
  - zarr
  - xarray
  - ipykernel
  - h5netcdf # For opening NetCDF files from cloud buckets.

  # Cloud & distributed compute
  - gcsfs
  - s3fs
  - fsspec
  - pathy
  - boto3
  - moto

  # Machine learning
  - pytorch::pytorch # explicitly specify pytorch channel to prevent conda from using conda-forge for pytorch, and hence installing the CPU-only version.

  # PV & Geospatial
  - pvlib
  - pyproj
  - rioxarray
  - geopandas

  # Development tools
  - pytest
  - flake8
  - jedi
  - mypy
  - black
  - pre-commit

  - pip:
      - git+https://github.com/SheffieldSolar/PV_Live-API
