general:
  name: on_premises
  description: Config for producing batches on OCF's on-premises hardware.
  cloud: local
input_data:
  base_path_or_bucket: /storage/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/
  nwp_zarr_path: zarr_intermediate/NWP/UKV__2018-01_to_2019-12__chunks__variable10__init_time1__step1__x548__y704__.zarr
  satellite_zarr_path: zarr_intermediate/EUMETSAT/all_zarr_int16_single_timestep.zarr
  solar_pv_path: raw/PV/PVOutput.org
  solar_pv_data_filename: UK_PV_timeseries_batch.nc
  solar_pv_metadata_filename: UK_PV_metadata.csv
  gsp_zarr_path: raw/PV/GSP/v0/pv_gsp.zarr
output_data:
  filepath: /storage/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v7/
process:
  seed: 1234
  batch_size: 32
  upload_every_n_batches: 0 # Write directly to output_data.filepath, not to a temp directory.
  forecast_minutes: 120
  history_minutes: 30
  satellite_image_size_pixels: 64
  nwp_image_size_pixels: 64
  nwp_channels:
    - t
    - dswrf
    - prate
    - r
    - sde
    - si10
    - vis
    - lcc
    - mcc
    - hcc
  prcesion: 16
  sat_channels:
    - HRV
    - IR_016
    - IR_039
    - IR_087
    - IR_097
    - IR_108
    - IR_120
    - IR_134
    - VIS006
    - VIS008
    - WV_062
    - WV_073
  val_check_interval: 1000
